server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  ##热部署工具
  devtools:
    restart:
      enabled: true  #开启热部署
      additional-paths: src/main/java #重启目录
      exclude: templates/**  #classpath目录下的templates文件夹内容修改不重启

rest-template:
  urls:
    payment: http://localhost:8001
