spring:
  application:
    name: payment
  profiles:
    active: dev #默认为开发环境
mybatis:
  mapper-locations: classpath*:com/huahun/payment/mapper/xml/*.xml
  type-aliases-package: com.huahun.payment.entity.po   #让mybatis自动扫描到自定义实体类