server:
  port: 8001

spring:
  application:
    name: payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:com/huahun/payment/mapper/xml/*.xml
  type-aliases-package: com.huahun.payment.entity.po   #让mybatis自动扫描到自定义实体类