server:
  port: 7001

spring:
  ##热部署工具
  devtools:
    restart:
      enabled: true  #开启热部署
      additional-paths: src/main/java #重启目录
      exclude: templates/**  #classpath目录下的templates文件夹内容修改不重启
