server:
  port: 7001

spring:
  ##热部署工具
  devtools:
    restart:
      enabled: true  #开启热部署
      additional-paths: src/main/java #重启目录
      exclude: templates/**  #classpath目录下的templates文件夹内容修改不重启
eureka:
  instance:
    hostname: server1.eureka.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://server2.eureka.com:7002/eureka/
